name: CI Selenium Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # O Ubuntu-latest já vem com Chrome, mas é bom garantir o setup
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Iniciar Aplicação
        # Usamos o 'nohup' para garantir que o processo continue rodando
        run: nohup mvn spring-boot:run > spring.log 2>&1 &

      - name: Aguardar Aplicação subir
        run: |
          echo "Aguardando porta 8080..."
          # Verifica se a aplicação responde 200 OK
          timeout 60s bash -c 'until curl -sI http://localhost:8080 | grep "200 OK"; do sleep 5; done'

      - name: Executar Testes com Maven
        # Adicionamos uma flag para forçar o modo headless se seu código aceitar propriedades
        run: mvn clean test -Dheadless=true